- name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      # ADD THIS SECTION BELOW
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }} # This ensures the report uploads even if tests fail
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
